name: "Podcast Generator"
autho: "Ray Villalobos"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    descriptoin: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    descriptoin: The committer's name
    required: true
    default: ${{ github.actor }}